name: ansible-lint

on:
  workflow_call:
    inputs:
      requirements-file:
        default: ""
        description: "Path to ansible requirements file to install dependencies"
        type: string

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: lint
        uses: ansible/ansible-lint@262624cd0ab22a4221293216856c59671ce7aa5e # v26.6.0
        with:
          requirements_file: ${{ inputs.requirements-file }}
