name: build-image

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
        description: Name of the docker image to build
      registry:
        type: string
        default: docker.io
        description: Name of the docker registry to use
      registry-namespace:
        type: string
        default: denniswitt
        description: Name of the docker registry user to use
      create-artifacts:
        type: boolean
        default: true
        description: Wheter or not github artifacts for images should be created
      build-args:
        type: string
        default: ""
        description: Build args to pass in form of yaml content each arg seperated by a new line
      amd64-build-args:
        type: string
        default: ""
        description: Build args that are only passed to the amd64 platform build
      arm64-build-args:
        type: string
        default: ""
        description: Build args that are only passed to the arm64 platform build

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
        include:
          - platform: linux/amd64
            build-args: ${{ inputs.amd64-build-args }}
          - platform: linux/arm64
            build-args: ${{ inputs.arm64-build-args }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: cache podman storage
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.local/share/containers/storage
          key: podman-storage-${{ matrix.platform }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: export architecture name (removing os prefix)
        run: |
          echo "PODMAN_ARCH=${PLATFORM#*/}" >>${GITHUB_ENV}
        env:
          PLATFORM: ${{ matrix.platform }}

      - uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
        id: meta
        name: Set image metadata
        with:
          images: ${{ inputs.registry }}/${{ inputs.registry-namespace }}/${{ inputs.image-name }}
          tags: |
            type=sha,format=long
          flavor: |
            suffix=-${{ env.PODMAN_ARCH }}

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2
        with:
          image: ${{ inputs.image-name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ${{ matrix.build-args }}
            ${{ inputs.build-args }}
          oci: true
          containerfiles: |
            ./Dockerfile
          platforms: ${{ matrix.platform }}

      - name: Copy image to file
        run: |
          podman save ${{ inputs.registry }}/${{ inputs.registry-namespace }}/${{ inputs.image-name }}:sha-${{ github.sha }}-${{ env.PODMAN_ARCH }} \
            --format oci-archive \
            -o /tmp/${{ github.sha }}-${{ env.PODMAN_ARCH }}-oci.tar

      - name: Upload digest
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ inputs.create-artifacts }}
        with:
          name: ${{ github.sha }}-${{ env.PODMAN_ARCH }}
          path: /tmp/${{ github.sha }}-${{ env.PODMAN_ARCH }}-oci.tar
          if-no-files-found: error
          retention-days: 1
