name: hadolint

on:
  workflow_call:
    inputs:
      dockerfile:
        default: "Dockerfile"
        description: The Dockerfile to lint
        type: string

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: ${{ inputs.dockerfile }}
