name: terraform-lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: setup tflint
        uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a # v6.3.0
        with:
          tflint_version: "v0.64.0" # renovate: datasource=github-releases depName=terraform-linters/tflint versioning=semver

      - name: lint terraform
        run: |
          tflint --init --call-module-type=all --enable-rule=terraform_documented_variables --recursive
