name: terraform-lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: setup tflint
        uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2
        with:
          tflint_version: "v0.63.1" # renovate: datasource=github-releases depName=terraform-linters/tflint versioning=semver

      - name: lint terraform
        run: |
          tflint --init --call-module-type=all --enable-rule=terraform_documented_variables --recursive
