name: terraform-lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5.0.0

      - name: setup tflint
        uses: terraform-linters/setup-tflint@v6.2.0
        with:
          tflint_version: "v0.59.1" # renovate: datasource=github-releases depName=terraform-linters/tflint versioning=semver

      - name: lint terraform
        run: |
          tflint --init --call-module-type=all --enable-rule=terraform_documented_variables --recursive
