name: terraform-lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: setup tflint
        uses: terraform-linters/setup-tflint@1cf010d3c7aef302051ccdb68c14c5dc2efa34ef # v6.3.1
        with:
          tflint_version: "v0.64.0" # renovate: datasource=github-releases depName=terraform-linters/tflint versioning=semver

      - name: lint terraform
        run: |
          tflint --init --call-module-type=all --enable-rule=terraform_documented_variables --recursive
