name: yaml-lint

on:
  workflow_call:
    inputs:
      yamllint-path:
        default: ""
        description: "Path to custom yamllint file"
        type: string

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          config_file: ${{ inputs.yamllint-path }}
